---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  
  vars:
    - ansible_python_interpreter: /usr/bin/python

  tasks:
  - name: install ssh key
    authorized_key: user=vagrant 
                    key="{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}" 
                    state=present